services:
  oracle-db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle_db
    environment:
      ORACLE_PWD: my_password
      ORACLE_CHARACTERSET: AL32UTF8
    ports:
      - "1521:1521" # Oracle listener
      - "5500:5500" # Enterprise Manager Express
    volumes:
      - oracle-data:/opt/oracle/oradata
    healthcheck:
      test:
        [
          "CMD",
          "bash",
          "-c",
          "echo 'SELECT 1 FROM dual;' | sqlplus -S system/my_password@localhost/XEPDB1",
        ]
      interval: 30s
      timeout: 10s
      retries: 10

volumes:
  oracle-data:
