services:
  redis:
    image: redis:7.2
    container_name: redis-db
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PORT=6379
      - REDIS_DATABASES=1
    command: redis-server --requirepass my-password --loglevel warning
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local
