networks:
  cassandra-net:
    driver: bridge
services:
  cassandra-db:
    image: cassandra:5.0
    container_name: cassandra_db
    hostname: cassandra1
    networks:
      - cassandra-net
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: "TestCluster"
      CASSANDRA_DC: "datacenter1"
      CASSANDRA_RACK: "rack1"
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_USER: cassandra
      CASSANDRA_PASSWORD: cassandra
    volumes:
      - cassandra-data:/var/lib/cassandra

volumes:
  cassandra-data:
  cache:
    driver: local
